### ISSUE TITLE
<no value> in test output

### ISSUE THREAD

**Issue by lindig** [mkaz/hastie#8]
Running hastie in the `test/` directory results in output with `<no value>`. Because I don't have `less`, I had modified the `hastie.json` (I don't expect this to be the problem):

```
  "ProcessFilters": {
  },
```

The generated files in `test/public` contain `<no value>` strings:

```
:public $ pwd
/Users/lindig/src/hastie/test/public
:public $ grep "no value" index.html 
    <li><a href="<no value>//zebra/hastie-intro.html">Hastie - A fast static site generator in Go</a></li>
    <li><a href="<no value>//zebra/zebras.html">Zebras</a></li>
```

It would be helpful if the keys for which values are missing would be printed.

**Comment by mkaz** [comment]
Thanks @lindog - wow, am I late on this reply. :-)

I ran into the same issue, and just ended removing less from the test config, it was too hard coded to a specific directory anyways.
